name = "FunGrad"
version = "0.1.0"
defaultTargets = ["fungrad"]

[[lean_lib]]
name = "FunGrad"

[[lean_exe]]
name = "fungrad"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/mathlib4"